# KOTS HelmChart custom resource
apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: composio
spec:
  chart:
    # name must match the chart name from the .tgz chart archive
    name: composio
    # chartVersion must match the chart version from the .tgz chart archive
    chartVersion: 0.1.0
 
  namespace: composio

  values:
    replicated:
      enabled: true
    global:
      environment: development
      domain: localhost
      registry: 
        name: "008971668139.dkr.ecr.us-east-1.amazonaws.com"
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'
    image: 
      # Get the pull secret name with ImagePullSecretName
      pullSecrets:
        - name: '{{repl ImagePullSecretName }}'